Magister new login method
Z3r0byte/Magis pull request #79
Opened 2019-02-05 17:45 UTC by UnderKoen

Heb de login methode herschreven zodat die weer werkt met de nieuwe magister methode

2019-02-06 12:22 UTC, Z3r0byte commented
Thanks! Ik kijk er vanmiddag naar :grinning:

2019-02-06 17:48 UTC, Z3r0byte commented
Vandaag gaat niet meer lukken helaas, morgen heb ik wel genoeg tijd

2019-02-07 15:49 UTC, Z3r0byte commented on app/src/main/java/net/ilexiconn/magister/Magister.java
> +        String accesToken = "";
accesstoken, not accestoken (two ss's)

2019-02-07 16:04 UTC, Z3r0byte requested changes
Ten eerste: mooi staaltje reverse engineering! :) 
Er zit wel een steeds terugkomende spelfout in: accessToken schrijf je met dubbel s. Het zou fijn zijn als je dit kon verbeteren. Verder zou het qua code-mooiheid beter zijn geweest om de http requests ook in HttpUtil te plaatsen, maar dat is niet zo erg.

Het is leuk om te zien dat iemand interesse heeft om een open-source app ook echt te verbeteren. Wel moet je er rekening mee houden dat ikzelf geen updates meer uitbreng en dat de app ook niet meer op de Play Store staat. Je Pull Request wordt natuurlijk gewaardeerd, maar er zal (zonder lullig te klinken) naast het accepteren verder niets mee gebeuren. Je kunt natuurlijk wel zelf je eigen fork op de Play Store zetten. Ik zou het dan wel op prijs stellen als je de naam veranderd om verwarring te voorkomen, maar dit is niet verplicht.

2019-04-28 15:17 UTC, UnderKoen commented
Heb de spelfouten er uitgehaalt en de http request naar httputil verplaast. Ik gebruik zelf de app niet, maar gebruikte dit project als java api, want de orginelen ilexicon api is klein beetje outdated. Dit project is ook enorm handig uitgekomen met het maken van een api voor de taal swift.

2019-04-28 15:44 UTC, Z3r0byte commented
Ziet er prima uit zo, thanks!

2019-04-28 15:44 UTC, Z3r0byte approved these changes

2019-04-28 15:47 UTC, merged

2019-04-28 15:56 UTC, Z3r0byte commented
Een vraagje nog: in je code maak je een request naar https://macister.nl/authcode.php. Hoe lang ben je van plan deze site online te houden? Misschien is het handig als je de broncode hiervan ook openbaar maakt zodat iemand deze ook zelf zou kunnen hosten.

2019-04-28 16:21 UTC, UnderKoen commented
Zolang mijn momentele methode werkt zal deze site online blijven. Ik probeer het ook te onderhouden.
[Source](https://gitlab.com/UnderKoen/macistersite/blob/master/authcode.php)

2019-04-28 16:24 UTC, Z3r0byte commented
Ah, super! Mooi project heb je trouwens, jammer dat ik geen Mac heb, anders had ik hem uitgeprobeerd :)